CREATE TABLE avaliacao
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usuario_id         BIGINT,
    ponto_turistico_id BIGINT,
    nota               INTEGER,
    comentario         VARCHAR(255),
    data_avaliacao     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_avaliacao PRIMARY KEY (id)
);

CREATE TABLE marca_visita
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usuario_id         BIGINT,
    ponto_turistico_id BIGINT,
    data_visita        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_marcavisita PRIMARY KEY (id)
);

CREATE TABLE ponto_turistico
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome      VARCHAR(255),
    descricao VARCHAR(255),
    latitude  DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    categoria SMALLINT,
    CONSTRAINT pk_pontoturistico PRIMARY KEY (id)
);

CREATE TABLE usuario
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome         VARCHAR(255),
    email        VARCHAR(255),
    senha        VARCHAR(255),
    data_criacao TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_usuario PRIMARY KEY (id)
);

ALTER TABLE avaliacao
    ADD CONSTRAINT FK_AVALIACAO_ON_PONTO_TURISTICO FOREIGN KEY (ponto_turistico_id) REFERENCES ponto_turistico (id);

ALTER TABLE avaliacao
    ADD CONSTRAINT FK_AVALIACAO_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES usuario (id);

ALTER TABLE marca_visita
    ADD CONSTRAINT FK_MARCAVISITA_ON_PONTO_TURISTICO FOREIGN KEY (ponto_turistico_id) REFERENCES ponto_turistico (id);

ALTER TABLE marca_visita
    ADD CONSTRAINT FK_MARCAVISITA_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES usuario (id);